* Header
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LaTeX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER: \usepackage{etoolbox}
#+LATEX_HEADER: \AtBeginEnvironment{minted}{\fontsize{10}{10}\selectfont}
#+LaTeX_CLASS: code-article 
#+HTML_HEAD: "<style type="text/css">.org-src-container{ background-color: #181830; color: #DDDDFF; font-size: 130%} </style>"
#+OPTIONS: title:nil ^:nil
#+BIND: org-latex-title-command ""
* GUT Documentation
** About
GUT is a testing platform, particularly well suited for testing inferior hardware over a telnet or ssh connection. GUT provides a flexible framework that allows for easy expansion by the user of existing functionality, while providing a simple, YAML-formatted syntax for running tests.

GUT has a simple structure. Tests are written in YAML format and are passed to the program. Tests specify a sequence, in which each member consists of an /interface/ and a set of corresponding /command functions/. An /interface/ is a class that specifies how connection and subsequent communication is performed. The associated /command functions/ are actions that can be performed for every entry in the sequence. They range from something as simple as setting a connection variable (Setting the username used during login, for example), to actually sending data over the interface or parsing the response. /Command functions/ are flexible, simple to write, and are always executed in a deterministic order.

The flexible interface abstraction provides GUT with the flexibility to be used to develop sophisticated tests for various systems.

** Usage
This section will give a brief introduction to writing proper YAML files for GUT with the default YAML parser.

*** Overview
YAML is used as the language of choice for GUT. It was chosen over XML due to the relative conciseness of the syntax, over JSON due to the support of multi-line strings, and over a custom solution due to the desire to use a standardized format. Below is a very simple example of a test.
#+BEGIN_SRC yaml
global:
  username: lucent
  password: notpassword
  interface: telnet
  log: logs/test2log
  print_response:

cmd:
  send: pwd
  wait_after_send: .5
#+END_SRC

Note that YAML is, like python itself, reliant on whitespace to designate structure. There are two blocks in the above snippet: a =global= block, and a =cmd= block. Top-level blocks such as these are parsed sequentially -- the =cmd= block is parsed only after GUT is finished with =global=. There are only three types of top-level blocks supported: =global=, =cmd= and =include=. An =include= block is used to include YAML code from another file into the current test. The =global= block specifies global settings that will be merged with every subsequent =cmd= block, until another =global= block overwrites the global settings. As such, the snippet above is equivalent to the following:

#+BEGIN_SRC yaml
cmd:
  username: lucent
  password: notpassword
  interface: telnet
  send: pwd
  wait_after_send: .5
  log: logs/test2log
  print_response:
#+END_SRC

The =cmd= block is responsible for sending data over an interface and performing analysis on the results. Each =cmd= block is a dictionary that maps "command functions" to their arguments. In the example above, =username= is a function with the argument "lucent", =wait_after_send= is a function with the argument 0.5, and =print_response= is a function with no argument. The order in which these functions appear in a block has no effect on how the block is executed; instead, these functions are run in an order determined by the /priority/ of the function. The priority of a function is a hardcoded numerical value assigned to each function; the higher the priority, the lower the priority-number, the earlier the function will be run in each block. 

In addition to the commands above, there are some commands functions which are dynamically included due to the command-line arguments. For example, in the block above, you see that there is no specification of the address of the target. This is because the GUT command-line argument =--address= was used to set the address. This value is used as the default, but it can be overwritten by manually inserting an =address: localhost= entry or similar in a block. Similarly, certain interfaces implicitly include their own commands into each command. For a telnet frame, there are two commands which are always inserted and hidden: =connect= and =capture=. The =connect= command function has a priority such that it is run after all connection parameters, such as "interface", "username" and "password", have been set. It opens a connection to the desired target, or returns an existing one if a previous command had already opened one. The =capture= command, on the other hand, is used to capture any responses from the target.

With these modifications (and if the command was run with =--address localhost=), the block above is also thus equivalent to:

#+BEGIN_SRC yaml
cmd:
  username: lucent
  password: notpassword
  interface: telnet
  send: pwd
  wait_after_send: .5
  log: logs/test2log
  print_response:
  connect:
  capture:
  address: localhost
#+END_SRC

Here's what GUT does, given the block above:
+ Set the frame attribute =username= to "lucent"
+ Set the frame attribute =password= to "notpassword"
+ Set the frame attribute =interface= to "sh"
+ Set the frame attribute =address= to "localhost"
+ Open a connection to the target, which uses frame attributes =username=, =password=, =interface= and =address=.
+ Send the text "pwd" down the connection to the target.
+ Wait for 0.5 seconds.
+ Capture the response.
+ Print the response.
+ Append the response to logfile "log/test2log".

This is all well and good, but what if we want to run functions that require a more complicated input than a string or a number? What about multiple arguments to functions? How can this be handled? The GUT parser handles multiple arguments by accepting a /dictionary/ (or /map/) of arguments. Here's an example:
#+BEGIN_SRC yaml
cmd:
  expect:
    array: [teststring, (?)error]
    regex: True
#+END_SRC
=expect= above is a function that accepts two arguments, =array= and =regex=, that match the parameters in the function definition. The expect definition also defines a default value for the =regex= argument, making it optional. This also leads into a demonstration of how the more compact argument passing shown previously works: In the event that a single argument is sufficient to run the command function, that argument can be passed directly to the function name. Thus, if we were willing to sacrifice regex support, the command could be rewritten as:
#+BEGIN_SRC yaml
cmd:
  expect: [teststring, (?)error]
#+END_SRC
This "optimization" makes it easier to write concise tests.

*** Complicated Example
Below is an example of a more complicated test, showing the flexibility of GUT.
#+BEGIN_SRC yaml
global:
  interface: bci
  username: lucent
  password: password
  reject: "error"
  send: /oam/hwVersion

cmd:
  address: 135.112.98.16
  store_regex:
    - "FPGA Version: (.*), CPLD Version: (.{3})"
    - "HwVersion: (.*) HwRef" 

cmd:
  address: 135.112.98.30
  check_regex:
    - "FPGA Version: (.*), CPLD Version: (.{3})"
    - "HwVersion: (.*) HwRef"  

global:
  interface: shell
  shell: sh
  print_response:
  send: pwd
  
cmd:
  store_regex:
    regexes: '/(\w+)\r\n'
    store_as: 'current_folder'

cmd:
  check_regex:
    regexes: '/(\w+)\r\n'
    check_as: 'current_folder'

#+END_SRC
What is this test doing? The first =global= block specifies several options to be used for the subsequent BCI commands: =interface=, =username= and =password=. It also specifies a =send= function, which means that for every subsequent =cmd= block, the message being sent will stay the same. Lastly, due to the =reject= command function, if, in the subsequent messages, the substring "error" occurs in the responses, GUT will throw an error.

Next are two =cmd= blocks. They both specify different board addresses, and one specifies =store_regex=, and the other specifies =check_regex=. The =store_regex= scans the response from the target for an expression matching the regex, and stores multiple values which match the sections within parentheses. The =check_regex= function performs the same match, except that instead of storing it, it compares with existing stored values. Thus, this test checks whether the captured FPGA version, CPLD Version and HwVersion are identical for both targets, without requiring knowing in advance of what those versions are. In order to use these commands (and, indeed, understand the terminology), it is strongly recommended that the user be familiar with regular expressions. 
#+BEGIN_EXAMPLE

❱ Beginning Iteration 1 of 1...
  ❱ Entering "temp.yaml"
    ❱ Found interface "bci"
  ❱ Sending bci frame
    ❱ Connected with interface "bci"
    ❱ Running send
    ❱ Running reject
    ❱ Running store_regex
      ❱ Regex "FPGA Version: (.*), CPLD Version: (.{3})" captured: "('0x060b', '0x2')", stored as "FPGA Version: (.*), CPLD Version: (.{3})"
      ❱ Regex "HwVersion: (.*) HwRef" captured: "('P1',)", stored as "HwVersion: (.*) HwRef"
  ❱ Sending bci frame
    ❱ Connected with interface "bci"
    ❱ Running send
    ❱ Running reject
    ❱ Running check_regex
      ❱ Regex "FPGA Version: (.*), CPLD Version: (.{3})" stored as "FPGA Version: (.*), CPLD Version: (.{3})" matches: "('0x060b', '0x2')"
      ❱ Regex "HwVersion: (.*) HwRef" stored as "HwVersion: (.*) HwRef" matches: "('P1',)"
    ❱ Found interface "shell"
  ❱ Sending shell frame
    ❱ Running shell
    ❱ Connected with interface "shell"
    ❱ Running send
    ❱ Running store_regex
      ❱ Regex "/(\w+)\r\n" captured: "('utest',)", stored as "current_folder"
    ❱ Running print_response
      ❱ 
      /home/aapollon/utest
        ❱ Sending shell frame
    ❱ Running shell
    ❱ Running send
    ❱ Running check_regex
      ❱ Regex "/(\w+)\r\n" stored as "current_folder" matches: "('utest',)"
    ❱ Running print_response
      ❱ 
      /home/aapollon/utest
        ❱ Leaving "temp.yaml"
❱ Iteration 1 Completed
#+END_EXAMPLE
** Reference
*** High-Level Blocks
**** include
Include blocks are used to read external yaml files and add their contents in-place. No checking is done on whether the file has been visited previously, and so it is possible for the tester to be put into an infinite loop by having two files include each other (generally not recommended!).

Example:
#+BEGIN_SRC yaml
include: other_test_file.yaml
#+END_SRC
**** global
Global blocks are used to specify command functions and arguments that are inherited by subsequent =cmd= blocks. In the event that there is a conflict between the two, behavior is determined by the data type of a conflict: If the data type is singular, like a string or an integer, then the =cmd= block value takes precedence; however, if it is a dictionary or a list, a merge is performed.

Example:
#+BEGIN_SRC yaml
global:
  interface: telnet
  username: andrew
  password: itsasecret
  expect: [error]

cmd:
  send: ls /
  expect: [bin]

cmd:
  username: jeff~!
  password: notsecret
  send: ls /
#+END_SRC
is equivalent to
#+BEGIN_SRC yaml
cmd:
  send: ls /
  expect: [bin, error]
  interface: telnet
  username: andrew
  password: itsasecret

cmd:
  username: jeff~!
  password: notsecret
  interface: telnet
  expect: [error]
  send: ls /
#+END_SRC

**** cmd
Command blocks are structures that represent commands being sent to a target. Each command block is composed of several command functions, which perform actions like setting variables, setting up a connection, transmitting data, or analyzing responses. The command functions in every command block are executed in deterministic order, determined by their priority.

Example:
#+BEGIN_SRC yaml
cmd:
  interface: ftp
  address: 127.0.0.1
  username: root
  password: root
#+END_SRC
*** Interfaces
**** Frame
/Frame/ is an unusable interface that serves as a basis for all other interfaces. It's included in this documentation because all command functions defined under /Frame/ are available for use in every other interface by design.

***** Command Functions
****** interface
******* Arguments:
(string) interface
******* Description:
Sets the interface. This is a required variable for any command frame.
******* Properties:
Priority: 0
Quiet: True
****** show_args
******* Arguments:
None
******* Description:
Activate the hook_show_args hook, which will print out all arguments for all command functions for the =cmd= frame.
******* Properties:
Priority: 0
Quiet: True
****** connect
******* Arguments:
None
******* Description:
Establish a connection using all available connection variables. Implicitly included in every frame; does not need to be explicitly included in a frame.
******* Properties:
Priority: 1
Quiet: True
****** print_time
******* Arguments:
(string) formatting = "%H:%M:%S"
******* Description:
Prints out the time with an optional argument that specifies the formatting.
******* Properties:
Priority: 0
Quiet: False
****** log
******* Arguments:
(string) filename
******* Description:
Append the sent and received strings to the file specified by the /filename/ argument.
******* Properties:
Priority: 100
Quiet: False
****** vars
******* Arguments:
(dictionary) dict
******* Description:
Sets the /variable/ dictionary, where every key in the input dictionary is replaced with the corresponding value. The replacement is applied whenever the /hook_var_replace/ hook is applied to a function argument.
******* Properties: 
Priority: 0
Quiet: False
****** wait_before
******* Arguments:
(float) wait_time
******* Description:
Wait for a specified period of time, prior to doing anything else.
******* Properties:
Priority: -1
Quiet: False
****** wait_after
******* Arguments:
(float) wait_time
******* Description:
Wait for a specified period of time, after doing everything else.
******* Properties: 
Priority: 100
Quiet: False
**** Interactive_Frame
/Interactive_Frame/ is an unusable interface that inherits from /Frame/ and is used for interactive frames -- those where the /send/ command function is present and generic commands can be sent over the interface.
***** send
****** Arguments:
(string) content
****** Description:
Send a string down the interface to the target
****** Properties:
Priority: 4
Quiet: True
***** capture
***** Arguments:
None
***** Description:
Try and capture any text that returned from the target.
***** Properties:
Priority: 7
Quiet: False
***** print_response
****** Arguments:
None
****** Description:
Print the capture response.
****** Properties:
Priority: 100
Quiet: False
***** print_send
****** Arguments:
None
****** Description:
Print the argument passed to the /send/ command function.
****** Properties:
Priority: 5
Quiet: False
***** reject
****** Arguments:
(string/list[string]) array,
(boolean) regex = False
****** Description:
For array or every string in array, if it appears in the captured responses, then the test fails. If regex is True, a regex match is checked instead.
****** Properties:
Priority: 8
Quiet: False
***** expect
****** Arguments:
(string/list[string]) array,
(boolean) regex = False,
(float) timeout = 10
****** Description:
Tries to capture all strings in /array/ before the the number of seconds specified by /timeout/ expires. If /regex/ is True, the matches are made with regular expressions. If not all members of /array/ are captured, the test fails.
****** Properties:
Priority: 6
Quiet: False
***** store_regex
****** Arguments:
(string/list[string]) regexes,
(string/list[string]) store_as,
****** Description:
Try to capture every regex in /regexes/. The contents of every match are stored in the global storage dictionary under the index specified by the corresponding entry in /store_as/. /store_as/ should be of the same type/size as /regexes/, if specified. If it isn't, it is automatically set to a copy of /regexes/.
****** Properties:
Priority: 10
Quiet: False
***** check_regex
****** Arguments:
(string/list[string]) regexes,
(string/list[string]) check_as,

****** Description:
Try to capture every regex in /regexes/. The contents of every match are compared, using the key specified by the corresponding entry of /check_as/, to the value stored in the global storage dictionary. /check_as/ should be of the same type/size as /regexes/, if specified. If it isn't, it is automatically set to a copy of /regexes/.
****** Properties:
Priority: 12
Quiet: False
***** wait_after_send
****** Arguments:
(float) wait_time
****** Description:
Wait for a specified period of time, after /send/.
****** Properties: 
Priority: 5
Quiet: False
**** telnet_Frame
A usable interface named "telnet" descended from /Interactive_Frame/ that connects via telnet. If /username/ is provided, the connection waits for the string "ogin" and then sends the provided /username/. If /password/ is provided, the connection waits for the string "assword" and then sends the provided /password/. The default port is 23, but can be changed by calling /port/. This interface uses the built-in =telnetlib=, and is thus cross-platform.
***** username
****** Arguments:
(string) username
****** Description:
Sets the connection username.
****** Properties:
Priority: 0
Quiet: True
***** password
****** Arguments:
(string) password
****** Description:
Sets the connection password.
****** Properties:
Priority: 0
Quiet: True
***** port
****** Arguments:
(int) port
****** Description:
Sets the connection port.
****** Properties:
Priority: 0
Quiet: True
***** address
****** Arguments:
(string) address
****** Description:
Sets the connection address.
****** Properties:
Priority: 0
Quiet: True
**** sh_Frame
A usable interface named "shell" that allows the opening of a local shell and the running of specified commands. Uses =Pexpect= to manage the connection, and so cannot be used on Windows.
***** shell
****** Arguments:
(string) shell = 'sh'
****** Description:
Sets the connection shell.
****** Properties:
Priority: 0
Quiet: True
**** ftp_Frame
A usable interface named "ftp" descended from /Interactive_Frame/ that connects via ftp. This interface uses the built-in =ftplib=, and is thus cross-platform.
***** username
****** Arguments:
(string) username
****** Description:
Sets the connection username.
****** Properties:
Priority: 0
Quiet: True
***** password
****** Arguments:
(string) password
****** Description:
Sets the connection password.
****** Properties:
Priority: 0
Quiet: True
***** address
****** Arguments:
(string) address
****** Description:
Sets the connection address.
****** Properties:
Priority: 0
Quiet: True
***** rcwd
****** Arguments:
(string) directory
****** Description:
Change the remote working directory.
****** Properties:
Priority: 0
Quiet: False
***** lcwd
****** Arguments:
(string) directory
****** Description:
Sets the local working directory.
****** Properties:
Priority: 0
Quiet: False
***** put
****** Arguments:
(string) filename,
(boolean) binary = True
****** Description:
Upload the file specified by /filename/ to the target. If binary = True, it is copied byte-for-byte; otherwise, end-of-line characters will be converted between different operating systems.
****** Properties:
Priority: 4
Quiet: False
***** get
****** Arguments:
(string) filename,
(boolean) binary = True
****** Description:
Download the file specified by /filename/ from the target. If binary = True, it is copied byte-for-byte; otherwise, end-of-line characters will be converted between different operating systems.
****** Properties:
Priority: 5
Quiet: False
**** bci_Frame
A usable interface named "bci" that connects to the /bci/ interface on a board.
***** username
****** Arguments:
(string) username
****** Description:
Sets the connection username.
****** Properties:
Priority: 0
Quiet: True
***** password
****** Arguments:
(string) password
****** Description:
Sets the connection password.
****** Properties:
Priority: 0
Quiet: True
***** address
****** Arguments:
(string) address
****** Description:
Sets the connection address.
****** Properties:
Priority: 0
Quiet: True
**** ARD546_Frame
A usable interface named "ard546" that connects to the /ard546/ interface on a board.
***** address
****** Arguments:
(string) address
****** Description:
Sets the connection address.
****** Properties:
Priority: 0
Quiet: True
**** scpi_Frame
A unusable interface that serves as the basis for all specialized scpi interfaces.
***** address
****** Arguments:
(string) address
****** Description:
Sets the connection address.
****** Properties:
Priority: 0
Quiet: True
**** N6900_Frame
A usable interface named "n6900" that used to communicate with the power supply n6900.
***** set_output
****** Arguments:
(string/int) state
****** Description:
Set the output of the power supply to 1/ON or 0/OFF.
****** Properties:
Priority: 3
Quiet: False
***** get_output
****** Arguments:
None
****** Description:
Get the current output state (Off or On)
****** Properties:
Priority: 4
Quiet: False
***** set_volt
****** Arguments:
(float) volt
****** Description:
Set the output voltage
****** Properties:
Priority: 3
Quiet: False
***** get_volt
****** Arguments:
None
****** Description:
Get the output voltage.
****** Properties:
Priority: 4
Quiet: False
***** set_current_limit
****** Arguments:
(float) limit
****** Description:
Set the current limit.
****** Properties:
Priority: 3
Quiet: False
***** get_current_limit
****** Arguments:
None
****** Description:
Get the current limit.
****** Properties:
Priority: 4
Quiet: False
**** MXA_Frame
A usable interface named "mxa" that allows for communication with Keysight MXA signal analyzers.
***** center_freq
****** Arguments:
(float) freq,
(string) unit = "MHz"
****** Description:
Set the center frequency.
****** Properties:
Priority: 3
Quiet: False
***** val_freq
****** Arguments:
(float) freq,
(string) axis = 'Y',
(int) marker = 12,
(string) unit = "MHz"
****** Description:
Get the value at a specified frequency. Reads off the value directly off the Y axis by default, and so the value returns depends on how the Y axis is calibrated.
****** Properties:
Priority: 4
Quiet: False
***** center_freq
****** Arguments:
(int) source = 1,
(float) threshold = 10 (in dB),
(float) excursion = -200 (in dB),
(string) sort = "FREQ"
****** Description:
Return a list of (Amplitude, Frequency) pairs, where /source/ specifies the signal source, /threshold/ specifies how far a value is above its neighbors to qualify, /excursion/ is a static minimum value to qualify, and /sort/ specifies the order in which peaks are sorted in the output.
****** Properties:
Priority: 4
Quiet: False
** Development
*** Overview
GUT is composed of several modules:
+ The main, or *gut.py*, is responsible for controlling program flow. 
+ The parser, *yaml_parser.py* by default, is responsible for reading a YAML file and converting it to a workable data structure.
+ Conman, in *conman.py*, is a singleton class that is used to transfer information between different parts of the program, handle messaging, and manage connections to different interfaces and addresses.
+ Interfaces are classes, descended from the class "Frame", that define a name, connection mechanism, command functions and helper functions to allow the tester to interact with another object in a useful way. 

*** Adding a command function
As referred to here, a /command function/ is a command that can be run inside a GUT command-block. GUT performs almost everything through these functions, for the purpose of architectural simplicity.

Command functions are defined in interface classes. Very broad functions that could be useful in any interface can be written in the /Frame/ class directly, to make them available everywhere. More targeted functions should be written wherever appropriate so that interfaces that have no need of the functions don't inherit it. 

Below is sample code used for the =log= function. A =@command= decorator specifies the priority, hooks and whether the function is quiet. Priority is required, as GUT needs to know how to prioritize different functions; the other two have sane defaults. The next line is the function definition itself. The first argument of every function must be used to pass the frame object itself, and subsequent arguments can be any other python object that can be interpreted by the parser. The passing of the frame object is handled by GUT itself, and every other argument is reliant on the testfile.

#+BEGIN_SRC python
      @command(priority = 100, hooks = [hook_show_args])
      def log(self, filename):
          """Low-priority function to log the sent and received messages to a given file."""
          try:
              infile = open(filename, 'a')
          except IOError:
              self.conman.ferror("Failed to open file " + filename + " for logging.")
          infile.write(self._send + "\n\n" + self._response + "\n\n")
          infile.close()
#+END_SRC

Several things to note:
+ Perhaps confusingly, "high" priority corresponds to a low value the "priority" function attribute. A priority of 0 will be run very early in the process, whereas 100 will be run very late.
+ Command functions are very flexible, and there are no restrictions on what code you put in them. Here, log is performing I/O operations. It's inefficient, because every single frame will be opening and closing the file, but it shouldn't be a bottlenecking issue.

*** Adding an interface
Interfaces are objects that define a connection and how to perform certain operations on it -- how to connect, how to send data, how to receive data -- and are used to allow for connections to be more flexible. All interfaces are stored under */interfaces*, and they all inherit from /Frame/ in *frame.py*. This section will analyze an existing interface under *telnet_frame.py*, which should make it trivial to write your own.

The header of the class includes any required objects and defines the class as inheriting from the /Interactive_Frame/ class. The /Interactive_Frame/ class itself inherits from /Frame/ and defines useful functions to allow the user to interact directly with the target, instead of relying on built-in functions to format and send any messages. 

The header also defines a class =interfacename=, which is the string that will be used by the rest of the program to differentiate between different interfaces. As such, the interfacename should be distinct from that of every other interface. Note that this particular interface uses telnetlib -- no code outside of the interfaces should know of the details of how the communication protocol works.
#+BEGIN_SRC python
import time
import telnetlib
import socket
from interfaces.frame import Interactive_Frame
from decorators import command

class telnet_Frame(Interactive_Frame):
    interfacename = "telnet"    
#+END_SRC

The /establishConnection/ method is used to establish a ready-to-use connection. The interface returns a connection object that will be stored in conman, and used whenever another command wants to use an interface with the same arguments. This function is required for all interfaces.
#+BEGIN_SRC python
    def establish_connection(self, address, username, password):
        """ Connection procedure for remote shell."""
        try:
            con = telnetlib.Telnet(address, 23, 10)
        except socket.timeout:
            return None
        con.expect(['ogin'.encode('ascii')])
        con.write(username.encode('ascii') + b"\n")
        con.expect(['assword'.encode('ascii')])
        con.write(password.encode('ascii') + b"\n")
        time.sleep(.2)
        return con
#+END_SRC

The /send_frame/ method accepts no arguments apart from /self/, and is responsible for sending the contents of =self.send["content"]= down the connection. This function is required for interfaces inheriting from /Interactive_Frame/.
#+BEGIN_SRC python
    def send_frame(self):
        """Transmit a frame object's content to intended recipient."""
        self._connection.write(self._send.encode('ascii') + b"\n")
#+END_SRC

The /expect_message/ method accepts two arguments: an array, and a timer. The array is a list of regexes which are to be looked for, and the timer specifies when the expect operation times out. This method is needed for the command functions "expect" to work, and allows "expect" itself to remain unchanged by different interfaces and connection backends. This method returns a tuple either =(None, True)= in the event of a timeout, or =(str, False)= in the event of a capture, where =str= is all the text leading up to the captured string, inclusive. This function is required for interfaces inheriting from /Interactive_Frame/.
#+BEGIN_SRC python
    def expect_message(self, array, timer):
        """Wait for a message from an array, return either a capture or a timeout."""        
        results = self._connection.expect([x.encode('ascii') for x in array], timer)
        if results[0] == -1:
            return (None, True) # Return no capture, timeout
        else:
            return (results[2].decode('ascii'), False) # Return capture, no timeout
#+END_SRC

The /capture_message/ method is used in lieu of the /expect_message/ method for capturing text in the event that we don't know what string to expect. The method below simply waits a short period of time, and then returns all text that arrived during that period. This function is required for interfaces inheriting from /Interactive_Frame/.
#+BEGIN_SRC python
    def capture_message(self):
        """Try to capture text without an "expect" clause."""
        time.sleep(.4)
        return self._connection.read_very_eager().decode('ascii')
#+END_SRC

The command functions below, /username/, /password/ and /address/, are used exclusively to set the attributes that will be read during connection. Note the underscore before the attribute; this is necessary to differentiate the attribute variable from the function, which is itself an attribute of each frame.
#+BEGIN_SRC python
################################################################################
#################### Command functions
    @command(0, quiet=True)
    def username(self, username):
        """Used to set the connection username, if any."""
        self._username = username        

    @command(0, quiet=True)
    def password(self, password):
        """Used to set the connection password, if any."""
        self._password = password

    @command(0, quiet=True)
    def address(self, address):
        """Used to set the connection address."""
        self._address = address

#+END_SRC


