global:
  interface: ard546
  vars:
    tx_freq: 750000 
    rx_freq: 782000
  print_response:

cmd:
  send: |
    [
    MESSAGE: TYPE=SET
    TRANSACTION: ID=1
    HEARTBEAT: STATE=DISABLE
    ]
  expect: "SETRESPONSE"


# CARRIERCFG 
cmd:
  send: |
    [
    MESSAGE: TYPE=SET
    TRANSACTION: ID=100
    CARRIERCFG: INDEX=1 TXCONTAINER=1 TX2CONTAINER=5 RX1CONTAINER=1 RX2CONTAINER=5 TXFREQ=tx_freq RXFREQ=rx_freq POWER=100 GRPSIZEDOWN=4 GRPSIZEUP=4 SIGTYPE=NONE CARRTYPE=LTE_10 STATE=ENABLE
    ]
  expect: "SETRESPONSE"


# // CARRIERCFG for band class 25 (high band, DAS_BAND_CONFIG=BC25)
# [
# MESSAGE: TYPE=SET
# TRANSACTION: ID=100
# CARRIERCFG: INDEX=1 TXCONTAINER=1 TX2CONTAINER=5 RX1CONTAINER=1 RX2CONTAINER=5 TXFREQ=1950000 RXFREQ=1870000 POWER=100 GRPSIZEDOWN=4 GRPSIZEUP=4 SIGTYPE=NONE CARRTYPE=LTE_10 STATE=ENABLE
# ]
